- hosts: master

  tasks:
    - name: Creates directory
      file:
        path: /home/ubuntu/argocd
        state: directory
    
    - name: copy argo-cd.yaml and ingress.yaml
      copy:
        src: "{{ item }}"
        dest: /home/ubuntu/argocd/{{ item }}
      with_items:
        - ./argo-cd.yaml
        - ./ingress.yaml

    - name: install ArgoCD
      shell: |
        kubectl create namespace argocd
        kubectl apply -n argocd -f /home/ubuntu/argocd/argo-cd.yaml

    - name: change service type to ingress
      shell: |
        kubectl apply -n argocd -f /home/ubuntu/argocd/ingress.yaml >> argocd_ingress.txt
      args:
        chdir: $HOME
        creates: argocd_ingress.txt
        
